### ISSUE TITLE
Sync with the main nodecg repo

### ISSUE THREAD

**Issue by Lange** [nodecg/nodecg-cli#56]
`nodecg-cli` has been a bit unloved in the past year or two. It's not been kept up-to-date with changes happening in NodeCG itself. Specifically, it doesn't know about all the current package manifest properties, and it still recommends `~0.8.0` as the default `compatibleRange`.

This project should be given a once-over to ensure it is sync'd with NodeCG itself.

**Comment by Lange** [comment]
@Hoishin or @Seldszar, would either of you potentially be interested in working on this? I've been really happy with the work you've been doing on the main repo, and I'm very appreciative of the help.

**Comment by Hoishin** [comment]
Hmm, am I confused or you are talking about `generator-nodecg` by chance?

**Comment by Lange** [comment]
Wow, yep, I literally opened this on the wrong repo. See, I definitely do need help keeping things running lmao.

**Comment by Hoishin** [comment]
Hahaha, well with that said, it could be good idea to combine the two CLI for NodeCG into one CLI. The problem would be it would exclude `generator-nodecg` part from yeoman ecosystem though.

**Comment by Lange** [comment]
I think for now we should keep `generator-nodecg` as-is, just to keep it down to a scope that is maintainable.

I'll close this and re-open on the correct repo lol.
