### ISSUE TITLE
Doesn't install on NodeJS 0.12

### ISSUE THREAD

**Issue by coral** [nodecg/nodecg-cli#6]
Seems that gaze 0.6.4 doesn't build under NodeJS 0.12 on OSX
Downgrading to NodeJS 0.11 for the moment

shama/gaze#175

**Comment by coral** [comment]
It seems that the entire build chain with nodegit and other stuff is broken with NodeJS 0.11, 0.12 and iojs.
0.10.x works though

**Comment by coral** [comment]
Should also be mentioned that i run OSX 10.10

**Comment by Lange** [comment]
Right now we're waiting for gaze to be updated for Node 0.12. We can't downgrade to gaze 0.5.x, as it breaks our watcher. Unfortunately, for the time being we're stuck with gaze 0.6.x and Node 0.10.

**Comment by Lange** [comment]
Fixed by #8
